### ISSUE TITLE
[Bug] "/trackrawstats show custom PlayedMinutes" shows ticks played

### ISSUE THREAD

**Issue by GlennSchner** [MC-Machinations/VanillaTweaks#12]
It appears the raw stats function for tracking minutes tracks ticks instead - the counter moves upward much faster than seconds.

Running Vanilla Tweaks v0.1.12

**Comment by GlennSchner** [comment]
In fact, I think all the stats that track time do so in ticks. Have tested with custom-LastDeath and custom-Minecart ride so far.

**Comment by Draycia** [comment]
`PlayedMinutes` uses the minecraft statistic `minecraft:play_one_minute` which, despite the name, tracks the number of ticks the player has played. This mirrors that behaviour.

**Comment by GlennSchner** [comment]
I'll preface this comment with the fact that I have no idea how coding these plugins works - is it possible to do some math (divide by 1200) before it's applied to the scoreboard?

**Comment by Prof-Bloodstone** [comment]
Unfortunately it isn't really straight forward. What can be done is to have 2 scoreboards - one which has an update target and is being updated by MC, and second which is a dummy and needs to be updated manually. You can then every tick read values from the first one, divide by 1200 and set the result in the second, dummy one.

This is very similar to how VT datapack does it - although yu need to use 3 scores for that - one for original raw score, second for calculations, and third one just copies values from the second one after calculation.

I guess it'd make sense to have it as it her a separate module (just how it is in VT datapack) or have it as an option in TrackRawStats module.

**Comment by Machine-Maker** [comment]
Use the `TrackStats` module with the `tas_PlayTimeHrs` objective
