### ISSUE TITLE
ERROR world is not a valid world!

### ISSUE THREAD

**Issue by ouchmytoe** [MC-Machinations/VanillaTweaks#25]
I installed VanillaTweaks 0.1.17 on my new Java 11 Paper server on ShockByte. I deleted the world folders. I started the server and got these messages on the console:

INFO Enabling VanillaTweaks v0.1.17
ERROR world is not a valid world!

I've no idea why this error is occurring.

**Comment by Machine-Maker** [comment]
Can you post the full log from the server?

**Comment by osscarlos** [comment]
I have this same error. Hope this log helps. It comes up when the server starts, but VT works  as intended. I'm using Papermc 
[latest (1).log](https://github.com/MC-Machinations/VanillaTweaks/files/6555672/latest.1.log)

**Comment by Machine-Maker** [comment]
@osscarlos your issue is actually a different issue, please open a new issue and post that error log there.

**Comment by Chad-Brouski** [comment]
@osscarlos If you renamed your world name when you generated it you have to put intead of world the name of the servers name
