### ISSUE TITLE
Cannot find net.minecraft.server.v1_17_R1.WorldServer

### ISSUE THREAD

**Issue by stack9** [MC-Machinations/VanillaTweaks#27]
Brand new server, after enabling some modules via config this happened:
[latest.log](https://github.com/MC-Machinations/VanillaTweaks/files/6719846/latest.log)

**Comment by Machine-Maker** [comment]
Yeah, problem with spawning spheres for now. Can disable it and everything should work fine then. If it doesn't, can report what else might be wrong.
