### ISSUE TITLE
Grave not claimable

### ISSUE THREAD

**Issue by il-syahmi** [MC-Machinations/VanillaTweaks#28]
As per the title, I enabled player grave but no one is able to claim theirs and it messes with the area since you can't remove the grave in any way. Any solution?

**Comment by Machine-Maker** [comment]
How are you claiming it? Like what action are you performing to retrieve it?

**Comment by il-syahmi** [comment]
I tried by left-clicking the grave with a sword on and it doesn't work so I thought maybe I need to empty my hand but that does not work either. How are we supposed to claim it?

**Comment by Prof-Bloodstone** [comment]
Did you try sneaking on/near it?
As per wiki: https://github.com/MC-Machinations/VanillaTweaks/wiki/Player-Graves

> When the player who died sneaks over the grave, all his items are put back into the original slots.

**Comment by il-syahmi** [comment]
Ah I didn't see that before, thanks!
