### ISSUE TITLE
(BUG) Powered Piston + Redstone Wrench = Headless Piston

### ISSUE THREAD

**Issue by James76931** [MC-Machinations/VanillaTweaks#29]
It is possible to power a piston and rotate it using the Redstone Wrench to create a headless piston block.
I'm using Purpur-1251 (MC: 1.17).

![image](https://user-images.githubusercontent.com/15969024/124449710-9ffff600-dd7b-11eb-8564-9707a2c6f0f7.png)

**Comment by Machine-Maker** [comment]
I'll have to look at how the datapack handles rotation of powered pistons. I admit, I didn't think to try rotating them. If anyone knows, post it here, but I imagine it just doesn't allow rotation if its powered.
