### ISSUE TITLE
Spam in console on login

### ISSUE THREAD

**Issue by UnknownVariables-here** [MC-Machinations/VanillaTweaks#33]
Hihi, love the plugin its one of my favorites. Im getting this spam in console upon player login
No other datapacks present yet and no plugins that adds recipes but this one so Im not sure if I have an config conflict

The error: https://pastebin.com/4UExzkft

My config: https://pastebin.com/HR3BZRPD

Much thanks

**Comment by Machine-Maker** [comment]
Both those pastebins seem to be private or pending moderation? Regardless, I can't actually see them.

**Comment by UnknownVariables-here** [comment]
Whoops theres two of these plugins and this isnt the one with these issues lol sorry

**Comment by Machine-Maker** [comment]
Can you link to the other one? I genuinely didn't realize there were multiple and I'd like to be able to point people elsewhere if this one is still missing something.

**Comment by teakivy** [comment]
Hey @UnknownVariables-here, I just read this (nearly a month later) I am indeed working on my own Vanilla Tweaks, and this is for my version. [github.com/teakivy/vanilla-tweaks](https://github.com/teakivy/vanilla-tweaks) This is an issue with minecraft/spigot itself and loading recipes that don't exist anymore, there is no fix for it (as far as i am aware), but there is a comment above the crafting-tweaks section saying to just ignore this, as it only happens the first time you join after changing recipes.
```yml
crafting-tweaks:
  # Select which Crafting Tweaks are enabled.
  # This will NOT be reloaded upon /vt reload, changing Crafting Tweaks requires a full server restart.
  # If tweaks are disabled after being previously enabled, you may have an error in the server console saying a recipe cannot be found. Disregard this message.
  ```
