### ISSUE TITLE
Persistent Heads do not properly stack with their source

### ISSUE THREAD

**Issue by Brickwrath** [MC-Machinations/VanillaTweaks#35]
Currently, if a player is holding several of a custom player head, place one, and break it, its name and data is retained, but it does not properly stack with the "source" stack.
All broken player heads of the same type stack correctly together though, creating two "stack types" of the "original" and the "picked-back-up" ones.

Seemed like unintended behavior, so I wanted to let you know.
Let me know if there's any further info/testing needed to help investigate!

**Comment by Prof-Bloodstone** [comment]
What server software are you running?
Paper does more aggressive NBT normalization, but when I tested it everything worked fine. Might need to forcefully normalize the NBT ourselves though.

**Comment by Brickwrath** [comment]
Ahh, I didn't think of that.
I'm currently running the latest on Purpur, a fork of Paper.

**Comment by Machine-Maker** [comment]
Can you run `/paper dumpitem` while holding each head (the ones that dont stack), and post the results here? I should spit out that in the console so you can copy/paste it easily.

**Comment by Brickwrath** [comment]
Here's the two items dump data:
https://pastebin.com/y5tfvWsU

The heads remain consistent after that first change though; so placing and picking it up every time after that stack correctly with the "new heads".

**Comment by Machine-Maker** [comment]
This is/will be fixed in 0.2.0 (Assuming you are using Paper).

**Comment by Brickwrath** [comment]
Awesome, thanks for the help and development!

**Comment by Machine-Maker** [comment]
@Brickwrath if you want to mess around with the 0.2.0 beta, you can [download it here](https://github.com/MC-Machinations/VanillaTweaks/releases).
