### ISSUE TITLE
Wrenches do not respect GriefPrevention Claims

### ISSUE THREAD

**Issue by LcorpOfficial** [MC-Machinations/VanillaTweaks#40]
When using the wrenches, you can rotate redstone components within others' claims that you do not have trust in. this behavior is bad for SMP server use cases. Please consider implementing a way for GriefPrevention/worldguard support.

**Comment by Machine-Maker** [comment]
Can you try the latest version from https://github.com/MC-Machinations/VanillaTweaks/releases and see if you still have that issue?

**Comment by LcorpOfficial** [comment]
issue persists with v0.2.0-beta.8, 

separately, might need a different issue for this but pistons also do not rotate with standing+right-click, cycles through 3 states when crouching, those being the current state, opposing current state, and up. if you place a comparator in between you and the piston and right click while standing it works correctly. need to face it from this perspective. red cross shows crosshair pointing; from this perspective it also moves anything that is inline from your perspective, such as the repeater in the image.
![image](https://user-images.githubusercontent.com/73314328/139633196-ee68f691-1d5b-42eb-b8d6-7430de68daa1.png)

**Comment by Machine-Maker** [comment]
@LcorpOfficial yeah, can you open a separate issue for that? thanks.

**Comment by Machine-Maker** [comment]
@LcorpOfficial WorldGuard and GriefProtection integration should be working now in https://github.com/MC-Machinations/VanillaTweaks/releases/tag/v0.2.0-beta.10 

Go ahead and leave the issue open, itll close automatically when this is merged into the master branch

**Comment by LcorpOfficial** [comment]
Sweet, I'll do testing as soon as my ISP gets their act together and gets me back online! Haha.

**Comment by LcorpOfficial** [comment]
testing on my server works perfectly! that's a game changer, thank you!
