### ISSUE TITLE
Pistons do not rotate with standing+right-click, other strange behavior

### ISSUE THREAD

**Issue by LcorpOfficial** [MC-Machinations/VanillaTweaks#41]
Pistons do not rotate with standing+right-click, cycles through 3 states when crouching, those being the current state, opposing current state, and up. if you place a repeater or comparator in between you and the piston and right click while standing it works correctly. need to face it from this perspective. red cross shows crosshair pointing; from this perspective it also moves anything that is inline from your perspective, such as the comparator in the image.
![image](https://user-images.githubusercontent.com/73314328/139633196-ee68f691-1d5b-42eb-b8d6-7430de68daa1.png)

**Comment by Machine-Maker** [comment]
@LcorpOfficial I can't replicate this. Are you sure you are using the plugin for this, not the datapack? The whole "rotates other things in the line of sight" sounds exactly like the datapack behavior.

Run `/datapack list` and `/plugins` and post the result.

**Comment by LcorpOfficial** [comment]
Sorry! You are correct, they were conflicting. Apparently the datapack was re-enabled between testing sessions. good to close.
