### ISSUE TITLE
i don'understand the command for enableing mods, can someone just leave me an example?

### ISSUE THREAD

**Issue by EEEEEEEVA** [MC-Machinations/VanillaTweaks#45]
i don'understand the command for enableing mods, can someone just leave me an example?

**Comment by Machine-Maker** [comment]
If you are using one of the pre-release builds from https://github.com/MC-Machinations/VanillaTweaks/releases, then it should be `/vt enable <module>`. You can also manually do it by editing the `modules.yml` file in the `plugins/VanillaTweaks` folder and then reloading the plugin with `/vt reload`.

If you have further questions about this or similar things, you should ask them on the discord (https://discord.gg/Np6Pcb78rr)

**Comment by EEEEEEEVA** [comment]
i meant i know /vt enable module but i do not understeand how should i write the name of the mod, so can i ask for an example?
