### ISSUE TITLE
Multiplayer sleep 1.18

### ISSUE THREAD

**Issue by ShowTeKPT** [MC-Machinations/VanillaTweaks#50]
Multiplayer sleep not working as intended. It shows up as enabled and when people sleep it appears on chat but everyone still needs to sleep.

**Comment by Machine-Maker** [comment]
Did you actually change the sleeping percentage?

**Comment by ShowTeKPT** [comment]
> Did you actually change the sleeping percentage?

I tried looking on the config files, but didn't find anything related to that

**Comment by Machine-Maker** [comment]
It uses the vanilla gamerule, same as the datapack. But you can configure it in game with `/mps admin config`

**Comment by ShowTeKPT** [comment]
Thanks it worked.
