### ISSUE TITLE
Reflection error with spawning spheres

### ISSUE THREAD

**Issue by srnyx** [MC-Machinations/VanillaTweaks#51]
https://paste.srnyx.xyz/tozakilura.sql
Purpur 1.17.1

**Comment by Machine-Maker** [comment]
Update to the latest release from https://github.com/MC-Machinations/VanillaTweaks/releases

**Comment by srnyx** [comment]
> Update to the latest release from [MC-Machinations/VanillaTweaks/releases](https://github.com/MC-Machinations/VanillaTweaks/releases)

What's the difference between Bukkit and Paper version?

**Comment by Machine-Maker** [comment]
There are 4 extra modules in the Paper one that require paper. If you’re on purpur, use the paper one. It’s for paper and all forks of paper.

**Comment by srnyx** [comment]
> There are 4 extra modules in the Paper one that require paper.

What are they?

**Comment by Machine-Maker** [comment]
> Also, what happened to Double Shulker Shells (same with Classic Fishing Loot)?

You should just use the datapack for those. They are incredibly simple, and I would argue better in datapack format than in a plugin, at least right now.

> What are they?

You can [look at this file](https://github.com/MC-Machinations/VanillaTweaks/blob/dev/0.2.0/TODO.md) to see the progress with all the modules.

In addition to that, the `PersistentHeads` module that makes skulls keep their custom name and lore when placed, and broken again.
