### ISSUE TITLE
Could not pass event PlayerBedLeaveEvent OR PlayerQuitEvent to VanillaTweaks v0.2.0-SNAPSHOT

### ISSUE THREAD

**Issue by SleepyCatten** [MC-Machinations/VanillaTweaks#53]
Hi,

I believe this is an issue with the MultiplayerSleep component.

I've pasted the current log of the server here, showing both types of error:
https://gist.github.com/SleepyCatten/123c580aaf82e47787ad97fb55ebb0bc

Please let me know if you need further details.

**Comment by Machine-Maker** [comment]
I’ll look at it later today, do you have a set of instructions to reliably reproduce the error appearing in the log? Also, please post your multiplayer sleep config file.

**Comment by SleepyCatten** [comment]
Thanks for the reply.

To reproduce:

1. Run a Paper 144 server with the Paper Tweaks plugin with MultiplayerSleep enabled.
2. Use to bed to sleep.

That was triggering it every time.

'# Worlds to count player's from
included-worlds:
  - "kaleidoscope"
defaults:
  '# Default display for new players. Can be one of: HIDDEN, BOSS_BAR, ACTION_BAR, CHAT
  display: "CHAT"
'# Color of the boss bar for players who have that as their display style. Can be one of: PINK, BLUE, RED, GREEN, YELLOW, PURPLE, WHITE
boss-bar-color: "WHITE"
'# When enabled, the weather cycle will reset to clear regardless of the current weather. When disabled, default vanilla weather behavior is active.
always-reset-weather-cycle: false

I ended up working around this by disabling it and setting the gamerule for 1.18 playersSleepingPercentage to 0

**Comment by Machine-Maker** [comment]
I can't replicate it that easily, or at all rather. What plugins do you have installed? I feel like there might be a conflict somewhere.

**Comment by Machine-Maker** [comment]
Also, can you quickly download the the zip from [here](https://github.com/MC-Machinations/VanillaTweaks/actions/runs/1679368201), under the Artifacts header and try out that build? I think I maybe fixed an issue, but I'm still not 100% on what's going on.

**Comment by SleepyCatten** [comment]
Hi. Just tried that version and the error message no longer appears. Unless someone else finds otherwise, it looks like you fixed it. Sorry for the slow response, by the by!

**Comment by Machine-Maker** [comment]
And the functionality works correctly? All as expected?

**Comment by SleepyCatten** [comment]
Worked fine. One player allowed the server to sleep without any issue.
