### ISSUE TITLE
FastLeafDecay Error: Could not pass event BlockBreakEvent to VanillaTweaks v0.2.0-SNAPSHOT

### ISSUE THREAD

**Issue by xSuffix** [MC-Machinations/VanillaTweaks#54]
Hi,

This error appeared occasionally in my console:
https://gist.github.com/xSuffix/d27d4a358954e17fdc4abb1c18a2ebbd
That's all I could find in the console related to this error.

I expect this to be caused by fast-leaf-decay but I also have the following modules enabled:
rotation-wrenches, cauldron-concrete, coordinates-hud, custom-nether-portals, multiplayer-sleep, nether-portal-coords, track-raw-stats, track-stats, unlock-all-recipes

My server is running Purpur 1522 (latest) and the unreleased version of VanillaTweaks found here:
https://github.com/MC-Machinations/VanillaTweaks/actions/runs/1679368201

I think this error occurred once when a player was using an afk tree farm but probably also when nobody used it.

**Comment by Machine-Maker** [comment]
@xSuffix do you have any other plugins or datapacks installed?

**Comment by xSuffix** [comment]
Yes I do.

Plugins (18): BlueMap, Celeste, CoreProtect, CreeperHeal2, DiscordSRV, Essentials, EssentialsChat, EssentialsDiscord, EssentialsSpawn, floodgate, Geyser-Spigot, GSit, LuckPerms, Pl3xMap, spark, VanillaTweaks, Vault, WorldEdit

Datapacks (2): Terralith 2, VanillaTweaks Crafting Tweaks

**Comment by Machine-Maker** [comment]
Yep, there's the issue. Terralith 2.0 modifies the vanilla `#minecraft:leaves` tag to include saplings. FastLeafDecay uses that to check if the blocks are in fact leaves. I can work around that tho.

**Comment by Machine-Maker** [comment]
Ok, should be fixed in <https://github.com/MC-Machinations/VanillaTweaks/releases/tag/v0.2.0-beta.15>
