### ISSUE TITLE
Documentation: Are modules disable or enabled by default?

### ISSUE THREAD

**Issue by ryantheleach** [MC-Machinations/VanillaTweaks#57]
I have an existing server using the datapacks, and I was considering using this to drop-in replace several of the ones using a large amount of the tick time.

However, At a glance I'm unsure whether I need to boot this up in a test server first, in order to generate the configs, in order to disable/enable the modules I'm not currently using, if they are all enabled by default.

Additionally, there appears to be no documentation on how much compatibility there is.

e.g. does it have the ability to migrate graves from the datapack version, etc.

**Comment by Machine-Maker** [comment]
Everything’s disabled by default for exactly that reason. 

p.s. In the future, please ask questions like this on the [discord](https://discord.gg/AQtdVW9)

**Comment by Machine-Maker** [comment]
As for migration, there is for some, but not all. And I plan to have it documented, but for now, if you’ve got specific questions about specific modules, just ping me on the discord.

**Comment by ryantheleach** [comment]
Apologies, I had discovered this via github, and missed the wiki badge linking to the documentation, and assumed the github wiki was the documentation.
