### ISSUE TITLE
/Back functionality 

### ISSUE THREAD

**Issue by Chroee** [MC-Machinations/VanillaTweaks#59]
The /back command works, in some cases but as reported by members (and my admin now) it doesn’t function the same as the original datapack’s /trigger command.

**Comment by Machine-Maker** [comment]
Can you go into detail about how it functions differently? Like what is expected, and what do you get?

**Comment by Chroee** [comment]
I believe that it works according to deaths, while the original is based on where you last teleported. I can have my members give me some details.
