### ISSUE TITLE
more mob heads, mob heads will not drop

### ISSUE THREAD

**Issue by Eris7090** [MC-Machinations/VanillaTweaks#64]
I have more-mob-heads set  to true but so far nothing has dropped a head. Is there a way to get more info in the console or somthing

**Comment by Machine-Maker** [comment]
what mob are you trying? and what version of the plugin are you running? Lots of mobs have very low drop chances

**Comment by Eris7090** [comment]
I tried a couple passive mobs like cows and pigs and I tried zombies creepers and skeletons as well. I tried both in survival and creative. I'm using version 0.20
https://github.com/MC-Machinations/VanillaTweaks/releases/tag/v0.2.0-beta.20

**Comment by Machine-Maker** [comment]
@Eris7090 well zombie and skeletons both have vanilla methods of getting their skulls. so this doesn't touch that. You have to kill a zombie or skeleton with a charged creeper to get those heads. 

Both cows and pigs have a drop rate of 1% with + 0.1% for each looting level.

**Comment by Eris7090** [comment]
oh okay my bad. I didn't know it was still vanilla style and that rare. thank you
