### ISSUE TITLE
Directions for /togglehud are incorrect

### ISSUE THREAD

**Issue by EUG01** [MC-Machinations/VanillaTweaks#7]
If you check with f3, you can see the directions are reporting wrong:
https://i.imgur.com/de2sgFb.png

**Comment by Prof-Bloodstone** [comment]
It was fixed a month before you created your issue: https://github.com/MC-Machinations/VanillaTweaks/commit/08a091bccece5be281fbd704cfd220def71dbb55#diff-fa6e4c53aab7006e3d6e6efcfcb1cf2fR84-R93

Works fine on latest.
