### ISSUE TITLE
Grave Looting

### ISSUE THREAD

**Issue by BobtheBob123456** [MC-Machinations/VanillaTweaks#70]
### Is your feature request related to a problem?

So basically, when someone dies they are the only person who can get there stuff from the grave. How about a feature is added so other people can loot peoples graves.

### Describe the solution you'd like

Basically make a command /toggle looting on so you can decide whether or not grave looting should be allowed.Graves.

By default looting is off.

### Describe alternatives you've considered

I don't have any.

### Other

I don't have any.

**Comment by Machine-Maker** [comment]
You know what I just realized, we have this. There is a `grave-robbing` configuration option. Set that to true and other players are able to loot anyones graves.
