### ISSUE TITLE
Permission for elevators

### ISSUE THREAD

**Issue by TaakoOfficial** [MC-Machinations/VanillaTweaks#74]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

Just add a permission for elevators 

### Describe alternatives you've considered

Just add a permission for elevators

**Comment by Machine-Maker** [comment]
There already is permissions for both use and creation. 
Use: `vanillatweaks.elevators.use`
Create: `vanillatweaks.elevators.create`

If there is something you want beyond this, we can re-open this.
