### ISSUE TITLE
Redstone Wrench Does Not Craft Correctly

### ISSUE THREAD

**Issue by jones6096** [MC-Machinations/VanillaTweaks#76]
### Expected behavior

![image](https://github.com/MC-Machinations/VanillaTweaks/assets/63066064/35b5e782-210c-4c6c-ae73-0efacc0ca3d5)
Crafting a redstone wrench should produce a carrot on a stick named "Redstone Wrench" with additional data applied

Correct Redstone Wrench from previous version (Pre 1.20) /data get entity @s SelectedItem or /paper dumpitem
![image](https://github.com/MC-Machinations/VanillaTweaks/assets/63066064/72c32934-6692-4461-8ef9-32fa500a2f1c)

### Observed/Actual behavior

![image](https://github.com/MC-Machinations/VanillaTweaks/assets/63066064/e0589b2a-4466-458d-acb0-906fbf570a16)
Carrot on a stick is crafted that appears to not have any of the intended data

### Steps/models to reproduce

Craft a redstone wrench with the latest plugin build 0.30 - beta 2 on Paper #45 or Purpur #2000

### Plugin and Datapack List

![image](https://github.com/MC-Machinations/VanillaTweaks/assets/63066064/f22de350-9b22-4bab-94f4-9a78e43c5021)
![image](https://github.com/MC-Machinations/VanillaTweaks/assets/63066064/c4e8d1b4-6249-4914-9dc9-9838fd4392b8)
![image](https://github.com/MC-Machinations/VanillaTweaks/assets/63066064/5494b09e-0ada-47cf-9c2a-9e2db27e830d)

Test server with just Paper 1.20.1 #45 and PaperTweaks 0.3.0 Beta 2

### Server Version Info

This server is running Paper version git-Paper-45 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: b169678)
You are running the latest version
Previous version: git-Paper-43 (MC: 1.20.1)

### Plugin Version

0.3.0-SNAPSHOT

### Other

Existing Redstone Wenches continue to function as expected

No errors are displayed in the console when attempting to craft the wrench

**Comment by Machine-Maker** [comment]
Yep, confirmed this is an issue. Will fix right now.
