### ISSUE TITLE
Invalid plugin.yml

### ISSUE THREAD

**Issue by Tikkle** [MC-Machinations/VanillaTweaks#8]
When loading VanillaPlus v0.1.12, it fails to load in due to a invalid plugin.yml

[https://pastebin.com/raw/ScnFc7ya](https://pastebin.com/raw/ScnFc7ya)

**Comment by Prof-Bloodstone** [comment]
@Tikkle Can't reproduce. Going by your logs, it looks like your plugin file is corrupted - hopefully you tried to re-download it :)
```
Caused by: java.util.zip.ZipException: error in opening zip file
```

**Comment by Machine-Maker** [comment]
Yeah, looks like Prof nailed it. Never had this issue. If you are *still* getting it, open another issue.
