### ISSUE TITLE
Task #103208 for PaperTweaks v0.4.0 generated an exception

### ISSUE THREAD

**Issue by EmanYm** [MC-Machinations/VanillaTweaks#80]
### Expected behavior

New elevators to be created by dropping an end pearl onto a wool block.

### Observed/Actual behavior

The ability to make new elevators has been halted due to a conflict with something I recently added.
When I drop a pearl on a wool block the following stack is spammed until I pick up the pearl.

> 20.11 23:59:16 [Server] WARN Task #103208 for PaperTweaks v0.4.0 generated an exception
20.11 23:59:16 [Server] INFO java.lang.NoSuchMethodError: 'org.bukkit.entity.Entity org.bukkit.World.spawn(org.bukkit.Location, java.lang.Class, java.util.function.Consumer)'
20.11 23:59:16 [Server] INFO at me.machinemaker.papertweaks.modules.experimental.elevators.ElevatorItemFinder.createElevator(ElevatorItemFinder.java:56) ~[PaperTweaks[v0.4.0].jar:?]
20.11 23:59:16 [Server] INFO at me.machinemaker.papertweaks.modules.experimental.elevators.ElevatorItemFinder.successCheck(ElevatorItemFinder.java:46) ~[PaperTweaks[v0.4.0].jar:?]
20.11 23:59:16 [Server] INFO at me.machinemaker.papertweaks.utils.runnables.ItemDropFinder.run(ItemDropFinder.java:53) ~[PaperTweaks[v0.4.0].jar:?]
20.11 23:59:16 [Server] INFO at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.1.jar:git-Purpur-2062]
20.11 23:59:16 [Server] INFO at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[purpur-1.20.1.jar:git-Purpur-2062]
20.11 23:59:16 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1506) ~[purpur-1.20.1.jar:git-Purpur-2062]
20.11 23:59:16 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.20.1.jar:git-Purpur-2062]
20.11 23:59:16 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1420) ~[purpur-1.20.1.jar:git-Purpur-2062]
20.11 23:59:16 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[purpur-1.20.1.jar:git-Purpur-2062]
20.11 23:59:16 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[purpur-1.20.1.jar:git-Purpur-2062]
20.11 23:59:16 [Server] INFO at java.lang.Thread.run(Thread.java:840) ~[?:?]

### Steps/models to reproduce

Attempt to generate an elevator by following the instructions on the wiki.

### Plugin and Datapack List

The creation of new elevators worked before I added ChestSort, PlayerWarps, HeadDatabase and Vault.
Elevators/PaperTweaks functioned as expected with all of the other plugins I have installed.

### Server Version Info

`Purpur 1.20.1-build 2062` provided by my host.
`PaperTweaks version 0.4.0` downloaded from hangar.

`HeadDatabase 4.18.2` from Spigot
`ChestSort 13.6.4` from Spigot
`PlayerWarps 6.29.0` also from SPigot
Vault is just vault.  It hasn't changed in over a year

### Plugin Version

`PaperTweaks version 0.4.0`

### Other

Anything that would go here has already been mentioned above

**Comment by Machine-Maker** [comment]
You are using an outdated version of minecraft (or a too new version of the plugin). The latest version only supports 1.20.2, and you are running 1.20.1

**Comment by EmanYm** [comment]
It's odd, it worked fine before I added the other things.  Oh well, I guess they will have to wait until I add the server to the rest of the network to get elevators again.
Thank you for your time, Maker
